import { DiscordLogoIcon, GitHubLogoIcon } from "@radix-ui/react-icons";
import {
  AlarmClock,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  BarChart3,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  Copy,
  CreditCard,
  Crop,
  DollarSign,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileTerminal,
  Filter,
  Footprints,
  HardHat,
  Image,
  Laptop,
  LayoutGrid,
  LogOut,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  PlusCircle,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Star,
  SunMedium,
  Trash,
  UploadCloud,
  User,
  Volume2,
  VolumeX,
  Wallet,
  X,
} from "lucide-react";

import {
  BMaCoffeSVG,
  FacebookSVG,
  GithubSVG,
  GoogleSVG,
  NextSVG,
  PatreonSVG,
  PaypalSVG,
  SpinnerSVG,
} from "~/components/Common/Icons/SVG";

export const Icons = {
  accessories: HardHat,
  add: Plus,
  addCircle: PlusCircle,
  alarm: AlarmClock,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  billing: CreditCard,
  calendar: CalendarDays,
  cart: ShoppingCart,
  chart: BarChart3,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronUp: ChevronUp,
  chevronUpDown: ChevronsUpDown,
  circle: Circle,
  close: X,
  clothing: Shirt,
  Coffe: BMaCoffeSVG,
  copy: Copy,
  crop: Crop,
  discord: DiscordLogoIcon,
  dollarSign: DollarSign,
  download: Download,
  edit: Edit,
  facebook: FacebookSVG,
  filter: Filter,
  Github: GithubSVG,
  github: GitHubLogoIcon,
  google: GoogleSVG,
  hide: EyeOff,
  horizontalSliders: SlidersHorizontal,
  horizontalThreeDots: MoreHorizontal,
  laptop: Laptop,
  logout: LogOut,
  menu: Menu,
  message: MessageSquare,
  microsoft: LayoutGrid,
  moon: Moon,
  nextjs: NextSVG,
  Patreon: PatreonSVG,
  Paypal: PaypalSVG,
  placeholder: Image,
  product: Package,
  remove: Minus,
  reset: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shoes: Footprints,
  spinner: SpinnerSVG,
  star: Star,
  store: ShoppingBag,
  sun: SunMedium,
  terminal: FileTerminal,
  trash: Trash,
  twitter: X,
  upload: UploadCloud,
  user: User,
  verticalSliders: Sliders,
  verticalThreeDots: MoreVertical,
  view: Eye,
  volume: Volume2,
  volumeMute: VolumeX,
  wallet: Wallet,
  warning: AlertTriangle,
};
